name: check-markdown
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0

    - uses: tj-actions/changed-files@bab30c2299617f6615ec02a68b9a40d10bd21366 # v45
      id: changed-files
      with:
        files: '**/*.md'
        separator: ","
        
    - uses: DavidAnson/markdownlint-cli2-action@db43aef879112c3119a410d69f66701e0d530809 # v17
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ","
        config: ./.github/.markdownlint.json
