name: mkdocs-build 
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          submodules: recursive

      # Checks-out submodules
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Checkout submodules
        shell: bash
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Swk"
          git config --global pull.rebase false
          git submodule add https://github.com/swisskyrepo/PayloadsAllTheThings/ docs
          mv docs/.github/overrides .

      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-committers-plugin
      - run: pip install mkdocs-material[imaging]
      - run: pip install mdx_truly_sane_lists
      - run: mkdocs gh-deploy --force

